### ISSUE TITLE
Undistort::readFromFile error

### ISSUE THREAD

**Issue by icedaigua** [tum-vision/LDSO#2] opened 2018-10-20 03:09 UTC
When I run 
run_dso_kitti \
             preset=0 \
             files=../../../02_datasets/KITTI/dataset/sequences/00/   \
             calib=./examples/Kitti/Kitti00-02.txt
I found an error  in function 
     void Undistort::readFromFile(const char *configFileName, int nPars, std::string prefix)  
in Undistort.cc.
  if (l3 == "crop") {
            outputCalibration[0] = -1;
            printf("Out: Rectify Crop\n");
        } else if (l3 == "full") {
  l3 == "crop"  return is 0.

I compile the code in Ubuntu 16.04.

**Comment by NikolausDemmel** [comment] 2018-10-20 09:30
Duplicate of https://github.com/JakobEngel/dso/issues/166

**Closed by NikolausDemmel** 2018-10-20 09:30 UTC
